### ISSUE TITLE
nginx配置基本用户鉴权

### ISSUE THREAD

**Issue by yuhongwei380** [yuhongwei380/Problem-record#61]
```
location / {
        auth_basic "Restricted Access";
        auth_basic_user_file /etc/nginx/.htpasswd;
        # 用户鉴权，使用.htpasswd文件存储用户名和密码
        root /usr/share/nginx/html;
        index index.html;
    }
```
利用htpasswd生成密码文件
```
sudo apt install apache2-utils
sudo htpasswd -c /path/to/.htpasswd2   snapchat
```
容器启动nginx并且导入卷：
```
version: '3.7'
services:
  nginx:
    image: nginx:mainline
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./test.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/:/etc/nginx/ssl/
      - ./.htpasswd:/etc/nginx/.htpasswd
      - ./:/usr/share/nginx/html
    restart: always

```
